#!/bin/tcsh




# Create subdirectory for verilog/VHDL files
if !( -f ${PWD}/HDL/GATE) then
  mkdir ${PWD}/HDL/GATE
endif

# Create subdirectory for verilog/VHDL files
if !( -f ${PWD}/HDL/PLACED) then
  mkdir ${PWD}/HDL/PLACED
endif



##############
# Synopsys DC
##############

# Create sdc directory 
if !( -f ${PWD}/design_compiler/SDC) then
  mkdir ${PWD}/design_compiler/SDC
endif

# Create dlib directory 
if !( -f ${PWD}/design_compiler/DDC) then
  mkdir ${PWD}/design_compiler/DDC
endif

if !( -f ${PWD}/design_compiler/SDF) then
  mkdir ${PWD}/design_compiler/SDF
endif

# Create RPT directory 
if !( -f ${PWD}/design_compiler/RPT) then
  mkdir ${PWD}/design_compiler/RPT
endif


# Create DESIGN_LIBS directory 
if !( -f ${PWD}/design_compiler/DESIGN_LIBS) then
  mkdir ${PWD}/design_compiler/DESIGN_LIBS
endif


# Create subdirectory for verilog/VHDL files
if !( -f ${PWD}/design_compiler/HDL/GATE) then
  mkdir ${PWD}/design_compiler/HDL/GATE
endif



##################
# Cadence innovus
##################

# Create DBS directory 
if !( -f ${PWD}/innovus/DBS) then
  mkdir ${PWD}/innovus/DBS
endif



# Create RPT directory 
if !( -f ${PWD}/innovus/RPT) then
  mkdir ${PWD}/innovus/RPT
endif

if !( -f ${PWD}/innovus/SDF) then
  mkdir ${PWD}/innovus/SDF
endif



###################
# Cadence Virtuoso
###################




if !( -f ${PWD}/virtuoso/calibre) then
  mkdir ${PWD}/virtuoso/calibre
endif


# Create drc, lvs, and pex directories
if !( -f ${PWD}/virtuoso/calibre/drc) then
  mkdir ${PWD}/virtuoso/calibre/drc
endif

if !( -f ${PWD}/virtuoso/calibre/drcmetalfill) then
  mkdir ${PWD}/virtuoso/calibre/drcmetalfill
endif

if !( -f ${PWD}/virtuoso/calibre/drcpolyfill) then
  mkdir ${PWD}/virtuoso/calibre/drcpolyfill
endif

if !( -f ${PWD}/virtuoso/calibre/lvs) then
  mkdir ${PWD}/virtuoso/calibre/lvs
endif

if !( -f ${PWD}/virtuoso/calibre/pex) then
  mkdir ${PWD}/virtuoso/calibre/pex
endif

# Create libs directory for your own librairies
if !( -f ${PWD}/virtuoso/libs) then
  mkdir ${PWD}/virtuoso/libs
endif

# Create simulation directory for Spectre/eldo/Hspice results
if !( -f ${PWD}/virtuoso/simulation) then
  mkdir ${PWD}/virtuoso/simulation
endif



##################
# Mentor Modelsim
##################
# Create RPT directory 
if !( -f ${PWD}/modelsim/PROJECTS) then
  mkdir ${PWD}/modelsim/PROJECTS
endif









